## Numpy

In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])

In [3]:
arr_1d

array([1, 2, 3, 4, 5])

In [4]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr_float = np.array([1, 2, 3], dtype=np.float64)

In [7]:
arr_float

array([1., 2., 3.])

In [10]:
zeros_arr = np.zeros((5, 4)) 

In [11]:
zeros_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
ones_arr = np.ones((3, 3), dtype=int) 

In [15]:
ones_arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
empty_arr = np.empty((4, 4)) 

In [20]:
empty_arr

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.11261095e-306],
       [8.34441742e-308, 1.78022342e-306, 6.23058028e-307,
        9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        1.78021527e-306],
       [8.34454050e-308, 1.11261027e-306, 1.15706896e-306,
        1.33512173e-306]])

In [21]:
identity = np.eye(3) 

In [22]:
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
range_arr = np.arange(0, 10, 2) 

In [24]:
range_arr

array([0, 2, 4, 6, 8])

In [27]:
linspace_arr = np.linspace(0, 1, 10) 

In [28]:
linspace_arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [36]:
random_int = np.random.randint(5, 10, size=(5, 5))

In [37]:
random_int

array([[6, 8, 9, 7, 7],
       [9, 8, 5, 7, 6],
       [8, 8, 5, 8, 9],
       [7, 5, 9, 9, 7],
       [8, 8, 7, 5, 8]], dtype=int32)

In [40]:
random_float = np.random.random((3, 4))

In [41]:
random_float

array([[0.75757404, 0.44897225, 0.18090545, 0.83903059],
       [0.6331515 , 0.86764951, 0.58554907, 0.19519168],
       [0.92516829, 0.7870737 , 0.99169307, 0.85996081]])

In [42]:
normal_dist = np.random.normal(0, 1, (3, 3)) 

In [43]:
normal_dist

array([[-0.47142342, -1.52363363,  0.89123655],
       [-0.7317165 , -0.12646175,  0.66983275],
       [ 2.60825303, -0.98835179,  0.48990402]])

In [55]:
np.random.seed(42)
np.random.randint(1, 5, size=(3, 3))

array([[3, 4, 1],
       [3, 3, 4],
       [1, 1, 3]], dtype=int32)

In [56]:
sample_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [57]:
sample_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
sample_array.shape

(3, 4)

In [59]:
sample_array.size

12

In [61]:
sample_array.max()

np.int64(12)

In [62]:
sample_array.mean()

np.float64(6.5)

In [63]:
sample_array.std()

np.float64(3.452052529534663)

In [64]:
sample_array.var()

np.float64(11.916666666666666)

In [66]:
sample_array.dtype

dtype('int64')

In [67]:
sample_array.ndim

2

In [68]:
sample_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
sample_array[2]

array([ 9, 10, 11, 12])

In [70]:
sample_array[0]

array([1, 2, 3, 4])

In [71]:
sample_array[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [72]:
sample_array[0:2, 1:2]

array([[2],
       [6]])

In [74]:
sample_array[1:2, 0:1]

array([[5]])

In [75]:
sample_array[2:3,1:3]

array([[10, 11]])

In [78]:
sample_array[0:3, 3:4]

array([[ 4],
       [ 8],
       [12]])

In [79]:
original = np.arange(12) 

In [80]:
original

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
sample_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [82]:
original.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
sample_array.reshape(1, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [84]:
sample_array.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [85]:
sample_array.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [87]:
sample_array.ndim

2

In [88]:
sample_array.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [90]:
sample_array.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [91]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [92]:
a

array([1, 2, 3, 4])

In [93]:
b

array([5, 6, 7, 8])

In [94]:
a+b

array([ 6,  8, 10, 12])

In [95]:
a-b

array([-4, -4, -4, -4])

In [96]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [100]:
a**3

array([ 1,  8, 27, 64])

In [101]:
a

array([1, 2, 3, 4])

In [104]:
data = np.random.normal(50, 15, 1000)

In [105]:
data

array([59.48174152, 35.31850028, 55.27836602, 51.99171047, 75.52544313,
       70.74717501, 26.99376911, 62.91691503, 68.97795877, 58.39038813,
       44.96881784, 86.20090873, 59.77113921, 79.64816411, 70.27217644,
       56.9620199 , 41.30448633, 49.63842683, 46.67131321, 31.78221567,
       59.75422362, 73.51029503, 45.52544758, 82.45484749, 26.63625821,
       65.81545323, 75.07280353, 46.93954129, 47.20915242, 65.64147764,
       57.58986665, 20.03882985, 37.34940268, 49.79675678, 29.4545273 ,
       42.88738525, 29.82971862, 44.44744054, 44.95065909, 55.27632015,
       48.62361014, 57.54184582, 55.75316011, 65.47009991, 63.10674561,
       61.52185753, 96.57301143, 55.21103955, 88.90357256, 56.18327603,
       48.75723628, 44.40252227, 72.64588698, 74.60755089, 58.99675784,
       67.00320162, 30.84169301, 26.76830266, 68.69490329, 48.09782753,
       61.23953626, 39.24068075, 74.85482705, 26.89371992, 29.2162237 ,
       71.66467376, 10.85237311, 55.67853302, 48.39011007, 38.96

In [106]:
data.mean()

np.float64(50.412295968092806)

In [107]:
data.std()

np.float64(15.005203095799828)

In [108]:
data.shape

(1000,)

In [109]:
data.max()

np.float64(96.57301142700084)

In [110]:
data.min()

np.float64(-0.27415775357017225)

In [111]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

In [112]:
arr1

array([[1, 2],
       [3, 4]])

In [113]:
arr2

array([[5, 6],
       [7, 8]])

In [114]:
arr3

array([[ 9, 10],
       [11, 12]])

In [115]:
np.vstack((arr1, arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [116]:
np.hstack((arr1, arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
#cython
#jython

In [117]:
np.nan

nan