In [1]:
import pandas as pd

In [4]:
df1 = pd.read_csv("22. messy_sales_data.csv")

In [5]:
df = df1.copy()

In [6]:
df['City'].unique()

<StringArray>
[ 'bangalore',      'DELHI',    'chennai',    'Jaipur ',    'Amdavad',
  'New Delhi',  'new delhi',    'Kolkata',  'hyderabad',     'mumbai',
   ' Lucknow',    'LUCKNOW',     'jaipur',  'Bengaluru',   'Calcutta',
     'MADRAS',  'bengaluru',     'Bombay',      'Poona',    'CHENNAI',
       'pune',   'CALCUTTA',    'Lucknow',    'kolkata',  'AHMEDABAD',
    ' Mumbai',  'Ahmedabad',       'PUNE',     'Jaipur',      'delhi',
    'KOLKATA',     'Mumbai',          nan,    ' Delhi ',  'HYDERABAD',
   'calcutta',     'bombay',    'amdavad',  'NEW DELHI',     'JAIPUR',
  'ahmedabad',      'poona',     'Madras',  'Bangalore',    'Chennai',
    'lucknow',   'Banglore',     'madras',  'BANGALORE',   'mumbai  ',
  'Hyderabad',     'BOMBAY',       'Pune',      'Delhi',   'banglore',
 ' Hyderabad',     'MUMBAI']
Length: 57, dtype: str

In [7]:
df['City']= df['City'].str.strip().str.lower()

In [8]:
df['City'].unique()

<StringArray>
['bangalore',     'delhi',   'chennai',    'jaipur',   'amdavad', 'new delhi',
   'kolkata', 'hyderabad',    'mumbai',   'lucknow', 'bengaluru',  'calcutta',
    'madras',    'bombay',     'poona',      'pune', 'ahmedabad',         nan,
  'banglore']
Length: 19, dtype: str

In [9]:
city_map = {
    'mumbai': 'Mumbai', 'bombay': 'Mumbai',
    'delhi': 'Delhi', 'new delhi': 'Delhi',
    'bangalore': 'Bangalore', 'bengaluru': 'Bangalore', 'banglore': 'Bangalore',
    'chennai': 'Chennai', 'madras': 'Chennai',
    'kolkata': 'Kolkata', 'calcutta': 'Kolkata',
    'hyderabad': 'Hyderabad',
    'pune': 'Pune', 'poona': 'Pune',
    'ahmedabad': 'Ahmedabad', 'amdavad': 'Ahmedabad',
    'jaipur': 'Jaipur',
    'lucknow': 'Lucknow',
    'unknown': 'Unknown'
}

In [11]:
df['City']= df['City'].map(city_map).fillna(df["City"].str.title())

In [12]:
df['City'].unique()

<StringArray>
['Bangalore',     'Delhi',   'Chennai',    'Jaipur', 'Ahmedabad',   'Kolkata',
 'Hyderabad',    'Mumbai',   'Lucknow',      'Pune',         nan]
Length: 11, dtype: str

In [14]:
df["City"].isnull().sum()

np.int64(2094)

In [15]:
df["City"].mode()

0    Chennai
Name: City, dtype: str

In [18]:
df["City"] = df["City"].fillna(df["City"].mode())

In [19]:
df["City"].isnull().sum()

np.int64(2094)

In [20]:
df["City"].unique()

<StringArray>
['Bangalore',     'Delhi',   'Chennai',    'Jaipur', 'Ahmedabad',   'Kolkata',
 'Hyderabad',    'Mumbai',   'Lucknow',      'Pune',         nan]
Length: 11, dtype: str

In [22]:
df["City"] = df["City"].fillna('Chennai')

In [23]:
df["City"].unique()

<StringArray>
['Bangalore',     'Delhi',   'Chennai',    'Jaipur', 'Ahmedabad',   'Kolkata',
 'Hyderabad',    'Mumbai',   'Lucknow',      'Pune']
Length: 10, dtype: str

In [24]:
df["City"].isnull().sum()

np.int64(0)

In [26]:
df["City"].unique()

<StringArray>
['Bangalore',     'Delhi',   'Chennai',    'Jaipur', 'Ahmedabad',   'Kolkata',
 'Hyderabad',    'Mumbai',   'Lucknow',      'Pune']
Length: 10, dtype: str

In [28]:
df["Category"].unique()

<StringArray>
[    'Grocery',      'SPORTS',  'electronic',    'Clothing',   'FURNITURE',
    'CLOTHING',      'BEAUTY',  'Furnitures',   'Clothings', 'electronics',
      'Beauty',        'TOYS',      'sports',      'beauty',     'grocery',
        'Book',      'Sports',   'Groceries', 'Electronics',        'book',
       'Books',     'GROCERY',   'Clothing ',       'books',   'furniture',
 'ELECTRONICS',   'Furniture',    'clothing',        'Toys',  'Electronic',
        'toys',         'Toy',       'BOOKS',         'toy',       'Sport']
Length: 35, dtype: str

In [29]:
df.columns

Index(['OrderID', 'CustomerID', 'CustomerName', 'City', 'Category',
       'PaymentMode', 'Price', 'Quantity', 'DiscountPct', 'Rating',
       'OrderDate', 'CustomerAge', 'Email', 'Phone', 'ReviewText'],
      dtype='str')

In [42]:
for col in df.columns:
    print()
    print( f"------------------column name {col}------------------")
    print(df[col].unique())
    print("==="*30)
    print()
   


------------------column name OrderID------------------
<StringArray>
[ 'ORD51058',  'ORD70248',  'ORD43804',  'ORD46367',  'ORD32922',  'ORD24549',
  'ORD33523',   'ORD5745',  'ORD89157',  'ORD59831',
 ...
  'ORD85628',  'ORD12262',  'ORD26366', 'ORD105705',  'ORD92081',  'ORD49057',
  'ORD60012',  'ORD78050',  'ORD68225',  'ORD72531']
Length: 105000, dtype: str


------------------column name CustomerID------------------
<StringArray>
['CUST04879', 'CUST00177', 'CUST04537', 'CUST07605', 'CUST03180', 'CUST07636',
 'CUST02017', 'CUST05552', 'CUST06968', 'CUST07512',
 ...
 'CUST07495', 'CUST08950', 'CUST02673', 'CUST07007', 'CUST07783', 'CUST05401',
 'CUST03113', 'CUST00727', 'CUST03384', 'CUST07869']
Length: 9000, dtype: str


------------------column name CustomerName------------------
<StringArray>
[      'Chaitanya Mane',        'Siddharth Sha', 'Nathaniel Chatterjee',
    'pranit contractor',   'Hemang Chakraborty',      '  Ishaan Nair  ',
      ' Tara Nagarajan',          'Waida 

In [43]:
df['Category'].unique()

<StringArray>
[    'Grocery',      'SPORTS',  'electronic',    'Clothing',   'FURNITURE',
    'CLOTHING',      'BEAUTY',  'Furnitures',   'Clothings', 'electronics',
      'Beauty',        'TOYS',      'sports',      'beauty',     'grocery',
        'Book',      'Sports',   'Groceries', 'Electronics',        'book',
       'Books',     'GROCERY',   'Clothing ',       'books',   'furniture',
 'ELECTRONICS',   'Furniture',    'clothing',        'Toys',  'Electronic',
        'toys',         'Toy',       'BOOKS',         'toy',       'Sport']
Length: 35, dtype: str

In [45]:
df['Category'] = df['Category'].str.strip().str.lower().str.rstrip("s")

In [46]:
df['Category'].unique()

<StringArray>
[   'grocery',      'sport', 'electronic',   'clothing',  'furniture',
     'beauty',        'toy',       'book',   'grocerie']
Length: 9, dtype: str

In [48]:
df['Category'] = df['Category'].str.replace('grocerie','grocery' )

In [49]:
df['Category'].unique()

<StringArray>
[   'grocery',      'sport', 'electronic',   'clothing',  'furniture',
     'beauty',        'toy',       'book']
Length: 8, dtype: str

In [50]:
df['Category'].isnull().sum()

np.int64(0)

In [51]:
df['Category'] = df['Category'].str.title()
df['Category'].unique()

<StringArray>
[   'Grocery',      'Sport', 'Electronic',   'Clothing',  'Furniture',
     'Beauty',        'Toy',       'Book']
Length: 8, dtype: str

In [52]:
df['PaymentMode'].unique()

<StringArray>
[     'net_banking',      'Net Banking',              'Upi',
              'COD',               'cc',       'Debit Card',
      'credit_card', 'Cash on Delivery',      'net banking',
      'NET BANKING',                nan,               'dc',
 'cash on delivery',      'Credit Card',               'DC',
      'CREDIT CARD',       'Netbanking',       'DEBIT CARD',
             'UPI ',       'debit card',              'cod',
              'UPI',              'upi',               'CC',
      'credit card']
Length: 25, dtype: str

In [54]:
payment_map = {
    'credit card':'Credit Card', 'cc':'Credit Card', 'credit_card':'Credit Card',
    'debit card':'Debit Card', 'dc':'Debit Card',
    'upi':'UPI',
    'cod':'Cash on Delivery', 'cash on delivery':'Cash on Delivery',
    'net banking':'Net Banking', 'netbanking':'Net Banking', 'net_banking':'Net Banking'
}

In [55]:
df['PaymentMode'] = df['PaymentMode'].str.strip().str.lower().map(payment_map)

In [56]:
df['PaymentMode'].unique()

<StringArray>
['Net Banking', 'UPI', 'Cash on Delivery', 'Credit Card', 'Debit Card', nan]
Length: 6, dtype: str

In [57]:
df['PaymentMode'].isnull().sum()

np.int64(3243)

In [64]:
df['PaymentMode'].mode()[0]

'Net Banking'

In [65]:
df['PaymentMode']= df['PaymentMode'].fillna(df['PaymentMode'].mode()[0])

In [67]:
df['PaymentMode'].isnull().sum()

np.int64(0)

In [68]:
df['Price'].unique()

<StringArray>
[    '904.48',    '1823.76',     '770.67',    '2028.06',     '604.00',
    '1271.25',    '1349.31',   '-1197.45',     '609.16',    '₹876.46',
 ...
     '279.18',  '₹1,256.77',     '995.12',    '1208.60',     '526.46',
    '-767.46',    '1048.24',  '₹1,854.93', 'Rs.1961.37', 'Rs.1468.22']
Length: 88579, dtype: str

In [70]:
type(df['Price'])

pandas.Series

In [71]:
df['Price'].dtypes

<StringDtype(storage='python', na_value=nan)>

In [73]:
df["Price"].astype("int")

ValueError: invalid literal for int() with base 10: '904.48'

In [78]:
df["Price"] = df["Price"].str.strip().str.replace("₹", "")

In [79]:
df["Price"].unique()

<StringArray>
[    '904.48',    '1823.76',     '770.67',    '2028.06',     '604.00',
    '1271.25',    '1349.31',   '-1197.45',     '609.16',     '876.46',
 ...
     '279.18',   '1,256.77',     '995.12',    '1208.60',     '526.46',
    '-767.46',    '1048.24',   '1,854.93', 'Rs.1961.37', 'Rs.1468.22']
Length: 86761, dtype: str

In [80]:
df["Price"] = df["Price"].str.replace("Rs.", "")

In [81]:
df["Price"].unique()

<StringArray>
[  '904.48',  '1823.76',   '770.67',  '2028.06',   '604.00',  '1271.25',
  '1349.31', '-1197.45',   '609.16',   '876.46',
 ...
   '279.18', '1,256.77',   '995.12',  '1208.60',   '526.46',  '-767.46',
  '1048.24', '1,854.93',  '1961.37',  '1468.22']
Length: 84495, dtype: str

In [83]:
df["Price"] = df["Price"].str.replace("-", "")

In [84]:
df["Price"].unique()

<StringArray>
[  '904.48',  '1823.76',   '770.67',  '2028.06',   '604.00',  '1271.25',
  '1349.31',  '1197.45',   '609.16',   '876.46',
 ...
   '977.41',   '279.18', '1,256.77',   '995.12',  '1208.60',   '526.46',
  '1048.24', '1,854.93',  '1961.37',  '1468.22']
Length: 82951, dtype: str

In [85]:
df["Price"].dtypes

<StringDtype(storage='python', na_value=nan)>

In [87]:
df["Price"] = df["Price"].str.replace(",", "")

In [90]:
df["Price"] = df["Price"].astype("float64")

In [91]:
df.dtypes

OrderID             str
CustomerID          str
CustomerName        str
City                str
Category            str
PaymentMode         str
Price           float64
Quantity        float64
DiscountPct       int64
Rating          float64
OrderDate           str
CustomerAge     float64
Email               str
Phone               str
ReviewText          str
dtype: object

In [93]:
df["Quantity"].unique()

array([ 3.,  4.,  1.,  2., -2.,  5., -5., -1., -3., -4.])

In [95]:
df["Quantity"] = df["Quantity"].abs()

In [96]:
df["Quantity"].unique()

array([3., 4., 1., 2., 5.])

In [99]:
df["Quantity"] = df["Quantity"].astype("int64")

In [100]:
df['Rating']

0         3.3
1         5.0
2         4.9
3         2.9
4         3.7
         ... 
106570    5.0
106571    3.3
106572    3.3
106573    4.6
106574    4.3
Name: Rating, Length: 106575, dtype: float64

In [101]:
df['Rating'].describe()

count    100129.000000
mean          3.409874
std           1.306731
min           0.500000
25%           2.600000
50%           3.300000
75%           4.100000
max           9.900000
Name: Rating, dtype: float64

In [102]:
df['Rating'].unique()

array([3.3, 5. , 4.9, 2.9, 3.7, 2.8, nan, 2.4, 1.1, 1.9, 4.5, 1.8, 3.2,
       1.7, 3.4, 3. , 2.1, 4.8, 3.1, 3.5, 3.6, 1.6, 2.2, 0.5, 3.9, 1.3,
       4.1, 4. , 1.4, 2.6, 4.4, 4.6, 4.7, 4.3, 2.5, 2.3, 5.6, 0.8, 2. ,
       1.5, 7.8, 3.8, 0.7, 2.7, 0.9, 4.2, 1.2, 9.4, 9.3, 8. , 0.6, 8.9,
       1. , 8.1, 7.6, 9.6, 6.8, 7.1, 8.3, 5.8, 5.5, 7. , 7.9, 6.4, 9.2,
       8.2, 8.7, 8.5, 7.7, 6.1, 9.5, 7.3, 6.2, 9.8, 7.2, 5.9, 9.9, 5.7,
       9. , 6.7, 6.5, 6.6, 6. , 8.6, 6.3, 7.5, 9.1, 8.8, 9.7, 8.4, 6.9,
       7.4])

In [103]:
df['Rating'] = pd.to_numeric(df['Rating'],errors= 'coerce')

In [104]:
df['Rating'].unique()

array([3.3, 5. , 4.9, 2.9, 3.7, 2.8, nan, 2.4, 1.1, 1.9, 4.5, 1.8, 3.2,
       1.7, 3.4, 3. , 2.1, 4.8, 3.1, 3.5, 3.6, 1.6, 2.2, 0.5, 3.9, 1.3,
       4.1, 4. , 1.4, 2.6, 4.4, 4.6, 4.7, 4.3, 2.5, 2.3, 5.6, 0.8, 2. ,
       1.5, 7.8, 3.8, 0.7, 2.7, 0.9, 4.2, 1.2, 9.4, 9.3, 8. , 0.6, 8.9,
       1. , 8.1, 7.6, 9.6, 6.8, 7.1, 8.3, 5.8, 5.5, 7. , 7.9, 6.4, 9.2,
       8.2, 8.7, 8.5, 7.7, 6.1, 9.5, 7.3, 6.2, 9.8, 7.2, 5.9, 9.9, 5.7,
       9. , 6.7, 6.5, 6.6, 6. , 8.6, 6.3, 7.5, 9.1, 8.8, 9.7, 8.4, 6.9,
       7.4])

In [105]:
(df['Rating'] < 0 ) 

0         False
1         False
2         False
3         False
4         False
          ...  
106570    False
106571    False
106572    False
106573    False
106574    False
Name: Rating, Length: 106575, dtype: bool

In [ ]:
(df['Rating'] > 5)

In [106]:
df.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
0,ORD51058,CUST04879,Chaitanya Mane,Bangalore,Grocery,Net Banking,904.48,3,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad
1,ORD70248,CUST00177,Siddharth Sha,Delhi,Sport,Net Banking,1823.76,4,20,5.0,04-01-2023,38.0,NaN,NaN,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,Chennai,Electronic,UPI,770.67,1,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,Cash on Delivery,2028.06,1,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN
4,ORD32922,CUST03180,Hemang Chakraborty,Ahmedabad,Furniture,Credit Card,604.00,4,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery


In [108]:
df.loc[0:100000:10000,["City", "Price", "OrderID"]]

,City,Price,OrderID
0,Bangalore,904.48,ORD51058
10000,Hyderabad,1163.12,ORD5068
20000,Hyderabad,515.60,ORD94030
30000,Delhi,405.97,ORD92683
40000,Bangalore,1377.23,ORD84537
50000,Delhi,1457.76,ORD94939
60000,Kolkata,633.14,ORD54005
70000,Chennai,1554.58,ORD52725
80000,Lucknow,1063.18,ORD4063
90000,Chennai,503.94,ORD12862


In [111]:
df.iloc[0::5000, 0::3]

,OrderID,City,Price,Rating,Email
0,ORD51058,Bangalore,904.48,3.3,chaitanya.mane@gmail.com
5000,ORD79486,Pune,704.69,3.5,yashawini.raj@rediffmail.com
10000,ORD5068,Hyderabad,1163.12,1.3,krishna.morar@rediffmail.com
15000,ORD75165,Bangalore,1098.29,3.4,bhavani.devi@hotmail.com
20000,ORD94030,Hyderabad,515.60,3.4,elijah.mitra@hotmail.com
25000,ORD46339,Kolkata,1207.32,3.6,anmol.chadha@outlook.com
30000,ORD92683,Delhi,405.97,2.2,jhalak.rau@yahoo.com
35000,ORD41431,Pune,398.51,4.0,chaman.lalla@hotmail.com
40000,ORD84537,Bangalore,1377.23,3.6,NaN
45000,ORD78382,Bangalore,5539.55,1.6,arya.shere@outlook.com


In [113]:
df.loc[0:100000:10000,0::2]


TypeError: cannot do slice indexing on Index with these indexers [0] of type int